name = "forbidden_stdlib"
version = "0.1.0"

description = "A cursed library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "DynamicCake", repo = "forbidden-stdlib" }
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
